//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Cap.Generales.BusinessObjects.Object;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;

namespace Cap.Generales.BusinessObjects.Direccion
{
    // [DefaultClassOptions]
    public partial class ItemDireccion : PObject // DevExpress.Persistent.BaseImpl.BaseObject
    {
        public ItemDireccion(DevExpress.Xpo.Session session)
            : base(session)
        {

        }
    }
}
